In [1]:
import mpi4py.MPI as MPI
import numpy as np

In [12]:
data = np.arange(20.0)
nprocs=6
# determine the size of each sub-task
ave, res = divmod(data.size, nprocs)
counts = [ave + 1 if p < res else ave for p in range(nprocs)]

# determine the starting and ending indices of each sub-task
starts = [sum(counts[:p]) for p in range(nprocs)]
ends = [sum(counts[:p+1]) for p in range(nprocs)]

# converts data into a list of arrays 
data = [data[starts[p]:ends[p]] for p in range(nprocs)]

In [32]:
data1=np.random.randint(0,10,(10,5))
data1

array([[4, 2, 1, 4, 2],
       [2, 2, 2, 3, 8],
       [4, 0, 8, 0, 0],
       [2, 4, 1, 0, 1],
       [1, 9, 6, 5, 4],
       [6, 2, 7, 9, 4],
       [7, 8, 3, 6, 5],
       [5, 4, 0, 6, 0],
       [1, 5, 8, 1, 5],
       [9, 2, 8, 8, 2]])

In [33]:
nprocs=6

In [35]:
# determine the size of each sub-task
ave, res = divmod(data1.shape[0], nprocs)
counts = [ave + 1 if p < res else ave for p in range(nprocs)]

In [36]:
print(ave)
print(res)
print(counts)

1
4
[2, 2, 2, 2, 1, 1]


In [37]:
# determine the starting and ending indices of each sub-task
starts = [sum(counts[:p]) for p in range(nprocs)]
ends = [sum(counts[:p+1]) for p in range(nprocs)]

In [38]:
print(starts)
print(ends)

[0, 2, 4, 6, 8, 9]
[2, 4, 6, 8, 9, 10]


In [45]:
# converts data into a list of arrays 
dataset = [data1[starts[p]:ends[p],:] for p in range(nprocs)]

In [46]:
dataset

[array([[4, 2, 1, 4, 2],
        [2, 2, 2, 3, 8]]),
 array([[4, 0, 8, 0, 0],
        [2, 4, 1, 0, 1]]),
 array([[1, 9, 6, 5, 4],
        [6, 2, 7, 9, 4]]),
 array([[7, 8, 3, 6, 5],
        [5, 4, 0, 6, 0]]),
 array([[1, 5, 8, 1, 5]]),
 array([[9, 2, 8, 8, 2]])]

In [48]:
dataset[4]

array([[1, 5, 8, 1, 5]])